### ISSUE TITLE
[ TypeError: file must have 'read' and 'readline' attributes ] downloading the assets for offline use

### ISSUE THREAD

**Issue by somnolent98** [mos9527/sssekai#11]
Downloading the assets seems to not be working

![image](https://github.com/user-attachments/assets/58804faa-2744-4b70-b401-97e0797251ae)

the first image is using i believe the 4.1.0 version, updating the abcache yields the same results

![image](https://github.com/user-attachments/assets/9c5ea42f-e2dd-4f0b-85f5-93c323ac20b3)
![image](https://github.com/user-attachments/assets/e2e61875-4f1c-4ff7-a2bc-af4daecb27ea)

**Comment by mos9527** [comment]
Should be fixed in [0.5.6](https://github.com/mos9527/sssekai/releases/tag/0.5.6)

**Comment by somnolent98** [comment]
Thanks a lot, I must've accidentally skipped over the new note after checking the wiki when it was updated for the web viewing of the file assets.
