### ISSUE TITLE
generator raised StopIteration

### ISSUE THREAD

**Issue by raymonable** [mos9527/sssekai#13]
I am coming into a problem when trying to download a specific bundle: `thumbnail/costume`.
It shows up in sekai.best, but I want a local version.

![image](https://github.com/user-attachments/assets/38b950e2-e8d8-47a0-b155-3c82db9e7238)

I am on the latest app hash, app version and sssekai version. My abcache is up to date.

**Comment by raymonable** [comment]
It does not show up in AssetStudio properly, so I assume it really didn't download the entire bundle and is more or less unusable.

**Comment by mos9527** [comment]
https://github.com/mos9527/sssekai/commit/f8598cbe9affb5900dd8f4cdfe9fa4349a0eb3f3 should fix it.
![image](https://github.com/user-attachments/assets/fa2040ba-a60e-4c7b-b891-1e0eca1ad092)
BTW you may want to check out `abserve` for [browsing the asset bundle index](https://github.com/mos9527/sssekai/wiki#exploring-the-cache).

**Comment by mos9527** [comment]
Github Actions seem to have broken too...this should be also fixed rn 😵‍💫
Now available on PyPI: https://github.com/mos9527/sssekai/releases/tag/0.5.9

**Comment by raymonable** [comment]
It works! Thank you.

Do you have a Kofi? I'd love to give a few dollars.

**Comment by mos9527** [comment]
> It works! Thank you.
> 
> Do you have a Kofi? I'd love to give a few dollars.

Thx! But that won't be necessary^^
I'll close this issue for now.
